name: CI/CD for Portfolio

# Trigger the workflow when `npm run predeploy` is triggered locally
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run build
      - name: Build project
        run: npm run build

      # Step 5: Optional - Add tests (placeholder)
      # Uncomment when tests are added
      # - name: Run tests
      #   run: npm test

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
